keys:
  - &gpg 23232A6D050ACE46DF02D72B84A772A8519FC163
  - &vmware age1w67vjhvfpm58sgr3rpz7chrxfplm9z4npw09dfy6p05jyeesyu8s9tlqtp
  - &tyo0 age1um59vuxencg3jty7y325x4sdfsnmwpghqvk7t7kaqrelayjpm4ssck7mnk
  - &ams0 age1ht8qv38vdrmuzehf8rpq9clm6uwk9q4w3qdkqcdjdfj9u2heeq3q0ep6dt
  - &sin0 age1q88jsfmck7f588fzqgsyx82kw7u22ha83zsshcv9l03tykwznv7sqfy2dp
creation_rules:
  - path_regex: secrets/.*
    key_groups:
    - pgp:
      - *gpg
      age:
      - *vmware
      - *tyo0
      - *ams0
      - *sin0
