keys:
  - &admin 23232A6D050ACE46DF02D72B84A772A8519FC163
  - &sys age166e9seuu932v0cr0nmeu0lnmy20r0ud5g34c34tmj92hrrngc9nq864amd
  - &home age159un2les797fnnejf9nmlxj6j8ymrryrv3vv0x2kkxxamat7mveqjyrp2x
creation_rules:
  - path_regex: config/secrets_uncrypted/.*
    key_groups:
    - pgp:
      - *admin
      age:
      - *sys
  - path_regex: config/secrets_home_uncrypted/.*
    key_groups:
    - pgp:
      - *admin
      age:
      - *home
