# ==============================================================================
# CDN Data — THE ONLY FILE THAT NEEDS HUMAN EDITING FOR CDN CHANGES
# ==============================================================================
# This file is the single source of truth for the ATC CDN infrastructure.
# Both Terraform (DNS records, CNAME mappings) and NixOS (DNS zones, Traefik
# proxies) consume this data.
#
# After editing this file, run terraform-pipe. Its existing output extraction
# writes lib/data/data.json, which is consumed directly by the ATC NixOS
# modules. There is no second CDN data file.
#
# To add a new CDN-accelerated service (e.g. "newapp" served by fra0):
#   a) Add `newapp = "fra0"` to cdn_services below.
#   b) Run terraform-pipe.
#   No other files need to change.
# ==============================================================================

locals {
  # ── Router hosts ─────────────────────────────────────────────────────────
  # The machines that run CoreDNS and act as authoritative NS for cdn.<domain>.
  # Must be names present in cdn_edge_nodes below.
  # The initial deployment uses fra0 as the sole authoritative NS. A second
  # NS can be added later after another router is actually deployed.
  cdn_ns_host = "fra0"

  # ── Edge nodes ───────────────────────────────────────────────────────────
  # Fields:
  #   name   – short hostname (matches networking.hostName on that machine)
  #   region – edge-node location tag (AP / HK / EU / US)
  #   weight – relative weight for round-robin DNS (higher = more traffic)
  #
  # IP addresses are taken from local.hosts in hosts.tf and exported in
  # cdn_data. They are not duplicated here, so CDN data cannot go stale.
  cdn_edge_nodes = [
    {
      name   = "tyo0"
      region = "AP"
      weight = 1
    },
    {
      name   = "tyo1"
      region = "AP"
      weight = 1
    },
    {
      name   = "hkg5"
      region = "HK"
      weight = 1
    },
    {
      name   = "sjc0"
      region = "US"
      weight = 1
    },
    {
      name   = "nue0"
      region = "EU"
      weight = 1
    },
    {
      name   = "fra0"
      region = "EU"
      weight = 1
    },
  ]

  # ── Services ─────────────────────────────────────────────────────────────
  # service-label → upstream-origin-hostname mapping.
  # The label is used as the subdomain: <label>.dora.im
  # The origin is the hostname of the compute node that actually runs the app.
  cdn_services = {
    jellyfin = "fra0"
    zone     = "fra0"
    alist    = "fra0"
    office   = "fra0"
    code     = "fra0"
    cloud    = "fra0"
    api      = "fra0"
    cpa      = "fra0"
    m        = "fra0"
    chat     = "fra0"
    cache    = "fra0"
    s        = "fra0"
  }

  # ── Terraform-usable derived values ──────────────────────────────────────
  # Map from edge node name to its properties (for for_each in resources).
  cdn_edge_nodes_with_addresses = [
    for n in local.cdn_edge_nodes : merge(n, {
      ipv4 = try(local.hosts[n.name].records.a.value, null)
      ipv6 = try(local.hosts[n.name].records.aaaa.value, null)
    })
  ]

}

# Output the full dataset consumed by lib/data/template.yq. The generated
# lib/data/data.json is an artifact, not a second CDN configuration file.
output "cdn_data" {
  description = "Full CDN dataset consumed by NixOS ATC modules"
  sensitive   = false
  value = {
    nsHost    = local.cdn_ns_host
    edgeNodes = local.cdn_edge_nodes_with_addresses
    services  = local.cdn_services
  }
}

# ==============================================================================
# Cloudflare DNS records derived from the data above
# ==============================================================================

# ── NS delegation for cdn.<domain> ───────────────────────────────────────────
# cdn.dora.im is delegated directly to fra0.dora.im for now. This is a normal
# child-zone delegation: the NS and its A/AAAA record live in the parent
# dora.im zone, while CoreDNS serves the child zone authoritatively.
resource "cloudflare_dns_record" "cdn_ns" {
  name    = "cdn.${cloudflare_zone.im_dora.name}"
  proxied = false
  ttl     = 3600
  type    = "NS"
  content = "${local.cdn_ns_host}.${cloudflare_zone.im_dora.name}"
  zone_id = cloudflare_zone.im_dora.id
}

# A/AAAA records for the NS host and edge nodes are generated by hosts.tf from
# the shared host inventory. This file exports those resolved values to Nix;
# it does not duplicate the parent-zone records.

# ── CNAME records for CDN-accelerated services ────────────────────────────────
# Each service label in cdn_services gets a CNAME:
#   <label>.dora.im → <label>.cdn.dora.im
# The cdn.dora.im authoritative server then answers with the edge pool IPs.
resource "cloudflare_dns_record" "cdn_service_cname" {
  for_each = local.cdn_services

  name    = "${each.key}.${cloudflare_zone.im_dora.name}"
  proxied = false
  ttl     = 1 # automatic
  type    = "CNAME"
  content = "${each.key}.cdn.${cloudflare_zone.im_dora.name}"
  zone_id = cloudflare_zone.im_dora.id
}
