{
 "title": "Hosts - Nix",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "hosts",
    "query": {
     "query": "label_values(node_time_seconds{job=\"hosts\"},instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "$hosts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "hosts" },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum((node_time_seconds{instance=\"$hosts\",job=\"hosts\"} - node_boot_time_seconds{instance=\"$hosts\",job=\"hosts\"}) OR vector(0))",
     "legendFormat": "Uptime"
    }
   ]
  },
  {
   "title": "Flake",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(nix_registry{name=\"self\",instance=\"$hosts\"} > 1)*1000",
     "legendFormat": "Version"
    },
    {
     "expr": "max(nix_registry{name=\"self\"})*1000",
     "legendFormat": "Newest"
    }
   ]
  },
  {
   "title": "Storage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 7, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "min" ] } },
   "targets": [
    {
     "expr": "avg by (instance, device) (node_filesystem_size_bytes{instance=\"$hosts\", fstype!~\"fuse.*|rclone\"} - node_filesystem_free_bytes{instance=\"$hosts\", fstype!~\"fuse.*|rclone\"} > 1000000000)",
     "legendFormat": "device={{device}},type=used"
    },
    {
     "expr": "avg by (instance, device) (node_filesystem_size_bytes{instance=\"$hosts\", fstype!~\"fuse.*|rclone\"} > 1000000000)",
     "legendFormat": "device={{device}},type=total"
    }
   ]
  },
  {
   "title": "RAM Usage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 13, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes{instance=\"$hosts\"} - node_memory_MemAvailable_bytes{instance=\"$hosts\"} or vector(0))",
     "legendFormat": "Used Memory"
    },
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"$hosts\"}",
     "legendFormat": "Total Memory"
    }
   ]
  },
  {
   "title": "System Load",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 7, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "scalar(node_load1{instance=\"$hosts\",job=\"hosts\"}) * 100 / count(count(node_cpu_seconds_total{instance=\"$hosts\",job=\"hosts\"}) by (cpu))",
     "legendFormat": "{{cpu}}"
    }
   ]
  }
 ]
}