# This list is largely copied from the chaos.social one.
# See it here: https://meta.chaos.social/federation

[followers_only]
"beta.birdsite.live" = "Avoid polluting timelines with Twitter posts"

[media_nsfw]
"sinblr.com" = "Untagged NSFW content"

[reject]
"activitypub-troll.cf" = "Spam"
"aethy.com" = "Lolicon"
"bae.st" = 'Discrimination, racism, "free speech zone"²'
"baraag.net" = "Lolicon"
"beta.birdsite.live" = "Twitter crossposter"
"birb.elfenban.de" = "Twitter crossposter"
"bird.evilcyberhacker.net" = "Twitter crossposter"
"bird.froth.zone" = "Twitter crossposter"
"bird.nzbr.de" = "Twitter crossposter"
"birdbots.leptonics.com" = "Twitter crossposter"
"birdsite.b93.dece.space" = "Twitter crossposter"
"birdsite.link" = "Twitter crossposter"
"birdsite.monster" = "Twitter crossposter"
"birdsite.slashdev.space" = "Twitter crossposter"
"birdsite.thorlaksson.com" = "Twitter crossposter"
"birdsite.wilde.cloud" = "Twitter crossposter"
"birdsitelive.treffler.cloud" = "Twitter crossposter"
"bridge.birb.space" = "Twitter crossposter"
"brighteon.social" = '"free speech zone"²'
"cawfee.club" = 'Discrimination, racism, "free speech zone"²'
"chudbuds.lol" = 'Discrimination, racism, "free speech zone"²'
"club.darknight-coffee.eu" = '"free speech zone"²'
"comfyboy.club" = "Discrimination, racism"
"daishouri.moe" = "Fascism, openly advertises with swastika"
"detroitriotcity.com" = 'Discrimination, racism, "free speech zone"²'
"eientei.org" = "Racism"
"eveningzoo.club" = "Racism"
"f.haeder.net" = "Admin is gay" # He isn't, but he's a TERF and a Very Proud Heterosexual(tm) so this is just to piss him off
"freeatlantis.com" = "Conspiracy theory instance"
"freecumextremist.com" = 'Discrimination, racism, "free speech zone"²'
"freefedifollowers.ga" = "Follower spam"
"freespeechextremist.com" = 'Discrimination, racism, "free speech zone"²'
"frennet.link" = 'Discrimination, racism, "free speech zone"²'
"gab.ai" = 'Discrimination, racism, "free speech zone"²'
"gab.com" = 'Discrimination, racism, "free speech zone"²'
"gameliberty.club" = '"free speech zone"²'
"gegenstimme.tv" = '"free speech zone"²'
"genderheretics.xyz" = 'Tagline "Now With 41% More Misgendering!"'
"geofront.rocks" = "Racism, transphobia, bigotry"
"gitmo.life" = '"free speech zone"²'
"glindr.org" = "Discrimination"
"glowers.club" = 'Discrimination, racism, "free speech zone"²'
"honkwerx.tech" = "Racism"
"iddqd.social" = 'Discrimination, racism, "free speech zone"²'
"itmslaves.com" = '"free speech zone"², noagenda affiliated'
"jaeger.website" = 'Discrimination, racism, "free speech zone"²'
"journa.host" = "Harmful behavior"
"kenfm.quadplay.tv" = "Conspiracy videos"
"kiwifarms.cc" = "Discrimination"
"libre.tube" = "Promotion of violence and murder, multiple other violations of our rules"
"lolicon.rocks" = "Lolicon"
"lolison.top" = "Lolicon"
"mastodon.ie" = "Block bot"
"mastodon.network" = "Imperaonation linking to porn"
"mastodon.popps.org" = "Homophobia"
"meta-tube.de" = "Conspiracy, CoVid19 denier videos https://fediblock.org/blocklist/#meta-tube.de"
"midnightride.rs" = "Discrimination"
"miss.mouse.services" = "Transphobia"
"monads.online" = "Has historically engaged in bad behavior"
"mstdn.foxfam.club" = "Right wing twitter mirror"
"newjack.city" = "Exclusive to unwanted follow bots"
"nicecrew.digital" = 'Discrimination, racism, "free speech zone"²'
"noagendasocial.com" = '"free speech zone"², harassment'
"ns.auction" = "Racism etc"
"ohai.su" = "Offline"
"outpoa.st" = '"free speech zone"'
"pawoo.net" = "Untagged nfsw content, unwanted follow bots, lolicon***"
"paypig.org" = "Racism"
"pieville.net" = "Racism, antisemitism"
"pl.info.natehiggers.online" = "Racism"
"pl.natehiggers.online" = "Racism"
"pl.tkammer.de" = "Transphobia"
"play.xmr.101010.pl" = "Cryptomining"
"pleroma.kitsunemimi.club" = "Discrimination"
"pleroma.narrativerry.xyz" = 'Discrimination, racism, "free speech zone"²'
"pleroma.nobodyhasthe.biz" = "Doxxing and discrimination"
"pleroma.rareome.ga" = "Doesn't respect blocks or status privacy, lolicons³"
"poa.st" = "Discrimination"
"poster.place" = "Racism"
"posting.lolicon.rocks" = "Racism, lolicon"
"qoto.org" = "Shitty behavior"
"rapemeat.solutions" = "Lolicon and also, like, the domain name"
"repl.co" = "Spam"
"ryona.agency" = "Bigotry"
"seal.cafe" = 'Discrimination, racism, "free speech zone"'
"shitpost.cloud" = '"Free speech zone"²'
"shitposter.club" = '"Free speech zone"²'
"shortstackran.ch" = "Racism"
"shota.house" = "Lolicon"
"skippers-bin.com" = "Same admin as neckbeard.xyz, same behaviour"
"sleepy.cafe" = "Bigotry"
"sneak.berlin" = "privacy violation"
"sneed.social" = "bigotry"
"social.ancreport.com" = 'Discrimination, racism, "free speech zone"²'
"social.lovingexpressions.net" = "Transphobia"
"social.teci.world" = 'Discrimination, racism, "free speech zone"'
"social.urspringer.de" = "Conspiracy, CoVid19 denier"
"socnet.supes.com" = 'Right wing "free speech zone"²'
"solagg.com" = "Scammers"
"spinster.xyz" = "Discrimination, TERFs"
"tastingtraffic.net" = "Homophobia"
"toot.canberrasocial.net" = '"free speech zone"²'
"truthsocial.co.in" = "Alt-right trolls"
"tube.kenfm.de" = "Conspiracy videos"
"tube.querdenken-711.de" = "Conspiracy videos"
"twitter.activitypub.actor" = "Twitter crossposting bots breaking mentions"
"twtr.plus" = "Twitter crossposting bots breaking mentions"
"varishangout.net" = "Transphobia, aggressive trolling"
"wiki-tube.de" = "Right wing conspiracy videos"
"wintermute.fr.to" = "Discrimination"
"wolfgirl.bar" = "Racism, holocaust denial"
"www.banepo.st" = "Harassment"
"yggdrasil.social" = "Discrimination"
"youjo.love" = "Actual child porn"
"zztails.gay" = "Racism"

