# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}: {
  alacritty-catppuccin = {
    pname = "alacritty-catppuccin";
    version = "f2da554ee63690712274971dd9ce0217895f5ee0";
    src = fetchFromGitHub {
      owner = "catppuccin";
      repo = "alacritty";
      rev = "f2da554ee63690712274971dd9ce0217895f5ee0";
      fetchSubmodules = false;
      sha256 = "sha256-ypYaxlsDjI++6YNcE+TxBSnlUXKKuAMmLQ4H74T/eLw=";
    };
    date = "2024-01-16";
  };
  alist = {
    pname = "alist";
    version = "v3.31.0";
    src = fetchurl {
      url = "https://github.com/alist-org/alist/releases/download/v3.31.0/alist-linux-musl-amd64.tar.gz";
      sha256 = "sha256-7J4mZcryqkErAfSRZMWjaK+wALa9Xe1w9RsUy9xOmsU=";
    };
  };
  clash-webui-yacd-meta = {
    pname = "clash-webui-yacd-meta";
    version = "b66b1d0393bd284b7a40329f95eae3746bb102be";
    src = fetchurl {
      url = "https://github.com/MetaCubeX/Yacd-meta/archive/b66b1d0393bd284b7a40329f95eae3746bb102be.zip";
      sha256 = "sha256-S6gLic5TeCkYDQsKmasr4/H5+ca8hP5qTzpVDXZHzdY=";
    };
    date = "2023-12-29";
  };
  kitty-catppuccin = {
    pname = "kitty-catppuccin";
    version = "d7d61716a83cd135344cbb353af9d197c5d7cec1";
    src = fetchFromGitHub {
      owner = "catppuccin";
      repo = "kitty";
      rev = "d7d61716a83cd135344cbb353af9d197c5d7cec1";
      fetchSubmodules = false;
      sha256 = "sha256-mRFa+40fuJCUrR1o4zMi7AlgjRtFmii4fNsQyD8hIjM=";
    };
    date = "2024-01-10";
  };
}
