# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}: {
  clash-meta = {
    pname = "clash-meta";
    version = "191243a1d2a8252c76092e65864e338f5e93db62";
    src = fetchFromGitHub {
      owner = "MetaCubeX";
      repo = "Clash.Meta";
      rev = "191243a1d2a8252c76092e65864e338f5e93db62";
      fetchSubmodules = false;
      sha256 = "sha256-yX6VeUxTv5DB+M9RFInQg4YL8+aqYUIXMwN3EayKlQQ=";
    };
    vendorSha256 = "sha256-XRCHW2KSuO4x5figh3A39sVgZMm/JMgPVRKaZUqSeTc=";
    date = "2023-08-03";
  };
  kitty-catppuccin = {
    pname = "kitty-catppuccin";
    version = "4820b3ef3f4968cf3084b2239ce7d1e99ea04dda";
    src = fetchFromGitHub {
      owner = "catppuccin";
      repo = "kitty";
      rev = "4820b3ef3f4968cf3084b2239ce7d1e99ea04dda";
      fetchSubmodules = false;
      sha256 = "sha256-uZSx+fuzcW//5/FtW98q7G4xRRjJjD5aQMbvJ4cs94U=";
    };
    date = "2023-06-09";
  };
}
