# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}: {
  clash-meta = {
    pname = "clash-meta";
    version = "574efb4526bd518c12236840238c39041fec286d";
    src = fetchFromGitHub {
      owner = "MetaCubeX";
      repo = "Clash.Meta";
      rev = "574efb4526bd518c12236840238c39041fec286d";
      fetchSubmodules = false;
      sha256 = "sha256-JwqQ8Gz9ZyRihkfGep7jaffXGoblKLxhoAuE8XM4luo=";
    };
    vendorSha256 = "sha256-My/fwa8BgaJcSGKcyyzUExVE0M2fk7rMZtOBW7V5edQ=";
    date = "2023-08-16";
  };
  kitty-catppuccin = {
    pname = "kitty-catppuccin";
    version = "4820b3ef3f4968cf3084b2239ce7d1e99ea04dda";
    src = fetchFromGitHub {
      owner = "catppuccin";
      repo = "kitty";
      rev = "4820b3ef3f4968cf3084b2239ce7d1e99ea04dda";
      fetchSubmodules = false;
      sha256 = "sha256-uZSx+fuzcW//5/FtW98q7G4xRRjJjD5aQMbvJ4cs94U=";
    };
    date = "2023-06-09";
  };
}
