name: "build cache"
on: [workflow_dispatch, push]

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  NIX_SECRET_KEY_FILE: /tmp/CACHE_KEY

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@main
    - name: Install nix
      uses: cachix/install-nix-action@master
      with:
        install_url: https://github.com/numtide/nix-unstable-installer/releases/latest/download/install
        nix_path: nixpkgs=channel:nixos-unstable
        extra_nix_config: |
          experimental-features = nix-command flakes
          system-features = kvm
          secret-key-files = /tmp/CACHE_KEY
          substituters = https://dora.cachix.org https://nix-community.cachix.org https://cache.nixos.org s3://nix?endpoint=g5s3.ph11.idrivee2-11.com
          trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= dora.cachix.org-1:H5tXs7A0WTxy+hYPGKTzKe2gRQDXGZfZb1NG7ZJ3MY4= nix-community.cachix.org-1:mB9FSh9qf2dCimDSUo8Zy7bkq5CX+/rkCWyvRCYg3Fs= dora-1:Jwud5q69IwWld/IqXW6nwBDx5s8WtsKpim+N5v+8fiE=
    - name: Setup CACHE_KEY
      run: 'echo "$CACHE_KEY" > /tmp/CACHE_KEY'
      env:
        CACHE_KEY: ${{ secrets.CACHE_KEY }}
    - name: Setup AWS
      run: |
        'echo "[default]\naws_access_key_id = $AWS_ACCESS_KEY_ID\naws_secret_access_key = $AWS_SECRET_ACCESS_KEY" >> ~/.aws/credentials'
    - name: build
      run: nix flake check --allow-import-from-derivation
    - name: push to s3
      run: |
        system=$(nix eval --impure --raw  --expr "builtins.currentSystem")
        nix copy --to "s3://nix?endpoint=g5s3.ph11.idrivee2-11.com" .#hydraJobs.all-checks.$system
