name: "build cache"
on: workflow_dispatch
env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@main
    - name: Install nix
      uses: cachix/install-nix-action@master
      with:
        install_url: https://github.com/numtide/nix-unstable-installer/releases/latest/download/install
        nix_path: nixpkgs=channel:nixos-unstable
        extra_nix_config: |
          experimental-features = nix-command flakes
          system-features = kvm
    - name: Setup CACHE_KEY
      run: echo "$CACHE_KEY" > /tmp/CACHE_KEY
      env:
        CACHE_KEY: ${{ secrets.CACHE_KEY }}
    - name: build
      run: nix sign-paths $(nix flake check)
    - name: push to S3
      run: nix copy --to "s3://nix?endpoint=g5s3.ph11.idrivee2-11.com"
