name: "eval"
on: workflow_dispatch

jobs:
  eval:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@main
    - name: Install nix
      uses: cachix/install-nix-action@master
      with:
        install_url: https://github.com/numtide/nix-unstable-installer/releases/latest/download/install
        nix_path: nixpkgs=channel:nixos-unstable
        extra_nix_config: |
          experimental-features = nix-command flakes
          system-features = kvm
    - name: Setup CACHE_KEY
      run: 'echo "$CACHE_KEY" > /tmp/CACHE_KEY'
      env:
        CACHE_KEY: ${{ secrets.CACHE_KEY }}
    - name: eval
      run: |
        system=$(nix eval --impure --raw  --expr "builtins.currentSystem")
        checks=$(nix eval --impure --json --expr "builtins.attrNames (builtins.getFlake \"$PWD\").checks.$system")
        echo $system
        echo $checks
        for check in $(echo "$checks" | jq -r '.[]'); do
          echo "--- upload $check"
          nix eval --json .#hydraJobs.all-checks.$checks
          echo
        done
