name: "tyo0"
on: workflow_dispatch

jobs:
  tyo0:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@main
    - name: Install nix
      uses: cachix/install-nix-action@master
      with:
        install_url: https://github.com/numtide/nix-unstable-installer/releases/latest/download/install
        nix_path: nixpkgs=channel:nixos-unstable
        extra_nix_config: |
          experimental-features = nix-command flakes
          system-features = kvm
    - name: Setup cachix
      uses: cachix/cachix-action@master
      with:
        name: dora
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
    - name: Set swap space
      uses: pierotofy/set-swap-space@master
      with:
        swap-size-gb: 10
    - name: build tyo0
      run: nix build .#nixosConfigurations.tyo0.config.system.build.image | cachix push dora
