traefik:
    KID: ENC[AES256_GCM,data:9jR4IMqjWaKaZPqbQOYUd1P02Pq+cg==,iv:ViKpqJ8eQkV0Sx5gOziqGrzAo/JsMhHhc93sxmbPLG0=,tag:M9XkCIcXEq3rfp4XZZmBgQ==,type:str]
    HMAC: ENC[AES256_GCM,data:rVW81ftUGxuCTIz8lecV8PhC5oFaYnvXUgUosSiMcIu6qeMxbkfZcapRiOE/jB2g789eWYVkniOg1Xa2J/Xl0wNr1e93h1x2YNke16U8pzhmwffl2mM=,iv:cIaelKjjCSPfnl+I10AvC4SdHtoL1AYamSTs9XnrHb0=,tag:qWbGsAEnoa6ohkRCuEoRUw==,type:str]
    CLOUDFLARE_DNS_API_TOKEN: ENC[AES256_GCM,data:RAk615l4Pxcd/bNCWeFSL/m31iwl/Znh+g3ZZ8nYpGQOkOMx0QFIyA==,iv:+Q5tJz1L0/Mpjjn/EiYfRGNB92ax6K6wa0lS4plUo+0=,tag:SQbeWGBM2qG5YRbFM5GF7Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1f723rc6ensk5x22m364mtltfzy95xv27fvalmxmg734aldd45drqqlkxts
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0UENnSEdMNjhCR3BCTm1R
            M21VdEZ6eUJoZ0N4WHBOMEF5Y3YyNkUwR3owCnZObFFwYktaTDBjdnQ4dmczN2hr
            VDU3RVRLUW16MnV2RGJDdVBnSGUxSEkKLS0tIHJqWjUvUXhPOWFMQzYxTFBUelhT
            cXdqRTBXY1hKZnhRd2UveTh3Ukl5RDgKAWsMBX/2Dts3893PSkathAgHwipRrrPu
            wkB2z3wKVfapGHCCbAcQ7Zf1EdYQqRrcJSP5fWMOmaq1Qqc13SuZOw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1f266lyrpxq6hejveyhlml9d64vtfrwqvkg8gsamgd8pkgxfprelqkgl97z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZYnM4a3pWeE8vWVFTLzhh
            bERUaWVaaFJ1WEZQQVpNdm9UaTJNak05bGtvCkxXYkt4ZFRiem9qWXpQczVacUVz
            RHBXdTluakhweGZJS0xyVExZL0k2cGcKLS0tIENzYS9NVStnczIydjVHY1ZkdFdH
            ZGlheUNLZGZvTW1BWGlsUVlkVytPTTQKbUTxBvffEXJLGulvqI59vysZpAtM9D/O
            gbscFv0vzbY8FiY2zWy8DixR2WcPse0do2LK8dSlGpDo/2fPX8FfUA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1um59vuxencg3jty7y325x4sdfsnmwpghqvk7t7kaqrelayjpm4ssck7mnk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKcjJPa2UrNHlmWEI0R0pR
            bnRrclg1TElyb0tHSUdzOTNZOWxLU1F1eWdnCmFKNDNBTEZwbm1XTG5Na1lESDha
            bjByT29MemhsQmxOWjRIdWprVDJ0bW8KLS0tIENDK0kvbnlNV3UwRGVMaG9lb1oz
            OTZHTktralRGZXdCeHl3dlRhaTZJL0UKd5SpjkWFadFcC9WYEQde7q0zUm+6h2Bh
            tHzL28mWaIGUE1K/cJ/ZvH/6rUSxzNMn21JGpL/uDT+xFUQqfv+U5A==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ht8qv38vdrmuzehf8rpq9clm6uwk9q4w3qdkqcdjdfj9u2heeq3q0ep6dt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOd0hoRzk0cEtBN2xtOTZE
            MXozRzlFa1dVaEJySHl5VWpEVm1TTS9FTDNjCjZVMk5heTFuZTJHZXdkbjVTUndI
            NGd4djJWUFBaL1V0eGU3ZnFDOTRQMFUKLS0tIElHWkZtaE5ZNzdJcmtEZGVCbmgx
            aC9MdlZCNFBudDZRK1MvUzQ0cDBnazgKJ1dTEeRiBXTdxK+ykaMnPDPzOC3i5fqK
            HOFus+EUnA9S7ooWMVYMW6hHgsSMz27js/9BMnr61DRwCJPyoX2MUA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1q88jsfmck7f588fzqgsyx82kw7u22ha83zsshcv9l03tykwznv7sqfy2dp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4Rk5ESHpyMGJ3ZmlCUTNr
            RGFLaGRrV3M4YjY4dXFES3Y4UjBuZDJHb0hzCk9TaTJPMDRzSjZ4cHBaYkZjSnl4
            aFVENGlBVzAyWVZ0UGorNW9PZUFtajgKLS0tIHRQMWZjSHlLWTVvK092WHFtREJF
            M0ROeHE1M1J0b1J3dFArZTgybzVMWW8KW8ql8Khadc14Ak1bHDLzVlOcvu4zi7ms
            Ev0+1xunQMBNuMbA+o50lvEKWOCnB5eCRxUlRPPrQ/nk+evYh91rrw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-08-05T14:15:03Z"
    mac: ENC[AES256_GCM,data:QwFqX33CBvuh7r5SFLN4fxy+tQikDelBkr1ehRk4lAMc1C4ebMQtSvyKk6ORw08LRnc3+LwIqeicrtCOePbECuGH5gmgybmVQIUPBiT6TAjGpUf9O1QbWpmeui0hpPS9L9EdYIOSpDdeMmCw9HCtp7qbM5GorBnWYQZNXbjIvno=,iv:FIMCChhtl2HK3MjhrWJ3MxTadA148vgN58wEy88pbBM=,tag:ARY2x+6RPowNmwYtGygAbA==,type:str]
    pgp:
        - created_at: "2022-10-18T08:04:11Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hF4DhQRDCIk4Ky8SAQdATQzYSf6vQ3eIeWf1a1wakjfaUpoPeUmsTtcL1+fXuVcw
            tpdXkJzHUiClNIGWUTHLDSgXoasZWkpGhua42QozAuABRU3TdaOrl5kqvTB7bgj0
            1GgBCQIQYC3IjbOX62//MLeGfgTHqmIWcOme5eSol+giqMVq74BcbgZWz5vf4wft
            +Snfg5S9XSl9iYeyuhoPOSlM6rY9Z06P4Kb0VCSa62b97PV1368Lj07jXnshLlRn
            gejRuUTVV+azLw==
            =zbIr
            -----END PGP MESSAGE-----
          fp: 23232A6D050ACE46DF02D72B84A772A8519FC163
    unencrypted_suffix: _unencrypted
    version: 3.7.3
